### ISSUE TITLE
Why does script entrypoint_workers.sh start the workers every hour?

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#119] opened 2021-06-07 15:05 UTC
Hi Jason, if you can find a minute to answer a question, I noticed that script entrypoint_workers.sh has a forever loop that runs script /var/www/MISP/app/Console/worker/start.sh once per hour.  Would you please explain why the CakeResque workers need to be started once per hour? I expect them to just keep going once started, what am I missing here? Thanks in advance.

**Comment by Kagee** [comment] 2021-06-16 12:28
https://github.com/coolacid/docker-misp/issues/5 pretty much explains it, the current status is "It's a simple way that works to make sure they are running, and waiting for misp upstream to rewrite their worker control"

**Comment by coolacid** [comment] 2021-06-16 16:12
@Kagee is correct. It's terrible, and I tried to go down the line to fix it but there is so many fixes that need to happen even upstream to MISP that it's not worth it. Closing as dupe of #5

**Closed by coolacid** 2021-06-16 16:12 UTC

**Comment by chrisinmtown** [comment] 2021-06-17 00:45
Thanks for clarifying, yes closing this is fine.
