### ISSUE TITLE
Background Jobs - Supervisor dependencies

### ISSUE THREAD

**Issue by Tux-Panik** [coolacid/docker-misp#192] opened 2022-10-12 21:26 UTC
Hi,

Since version 2.4.151, the legacy Scheduled Tasks based on CakeResque are no longer supported and the developers team of MISP recommends to migrate to Background Jobs using Supervisor. 

A [public migration guide](https://misp.github.io/MISP/background-jobs-migration-guide/)  has been released but focuses on standalone installations; which are not fully applicable in Docker context, due to network/proxy availability. 

As described in the first section, most of the prerequisites are not installed in the latest Docker version; which requires to install them manually and to save the container as an image, for persistence purpose.

Would it be possible:
 1. to include the prerequisites within the next MISP Docker image,
 2. to include within the Docker-Compose.yaml file the Supervisor configuration's mandatory fields,

To provide tips, I got the crontab records to be used to run a server PullAll as well as a feed CacheAll. 

Thanks for your valuable work and contributions to #Infosec community.
Regards,

**Comment by coolacid** [comment] 2022-10-12 21:42
Duplicate of #184

**Closed** 2022-10-12 21:42 UTC
