### ISSUE TITLE
Export Event/ Download event in STIX format fails

### ISSUE THREAD

**Issue by abhijeetasawant** [coolacid/docker-misp#146] opened 2021-10-29 13:45 UTC
Looks like typing.TypedDict doesn't exist at runtime in 3.7 , Need to update python to 3.8

Logs:
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 34, in <module>
    from misp_stix_converter import MISPtoSTIX20Parser, MISPtoSTIX21Parser
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/__init__.py", line 3, in <module>
    from .misp_stix_converter import misp_attribute_collection_to_stix1, misp_collection_to_stix2_0, misp_collection_to_stix2_1, misp_event_collection_to_stix1, misp_to_stix1, misp_to_stix2_0, misp_to_stix2_1
  File "/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/misp_stix_converter.py", line 22, in <module>
    from typing import List, TypedDict, Union
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/lib/python3.7/typing.py)

**Comment by coolacid** [comment] 2022-01-05 14:39
The requirement for 3.8 wasn't due until this month. I'll be working on a new docker container using the latest debian release this week which should include a newer python version.

**Comment by coolacid** [comment] 2022-01-05 14:39
Dupe of #128

**Closed by coolacid** 2022-01-05 14:39 UTC
